apiVersion: v1
kind: Namespace
metadata:
  name: ci

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: ci
spec:
  ports:
  - port: 8080
    name: jenkins-8080
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
  - port: 50000
    name: jenkins-50000
    targetPort: 50000
    protocol: TCP
  type: NodePort
  selector:
    app: jenkins

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-master
        image: jenkins
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins
        ports:
          - containerPort: 8080
            name: jenkins-8080
            protocol: TCP
          - containerPort: 50000
            name: jenkins-50000
            protocol: TCP
      volumes:
      - name: jenkins
        hostPath:
          path: /vagrant/jenkins